//Add non-agent stimuli picture filenames (240x360 px) and strings here
var stims = {
	stimDir: "",
	stimuli: ["filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",		
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",	
	],
	prompts:[
"Digitaalisten työkalujen käyttöä pitäisi opettaa enemmän oppilaitoksissa.",
"Työnhakutaitoja pitäisi opettaa enemmän oppilaitoksissa.",
"Pitäisikö oppilaitoksissa opettaa verkon ryhmätyöskentelyssä tarvittavia ohjelmien käyttöä enemmän (esim. Zoom, Teams)?",
"Pitäisikö oppilaitoksissa opettaa sosiaalisia taitoja, joita tarvitaan kasvokkain kohtaamisissa?",
"Pitäisikö oppilaitoksissa opettaa sosiaalisia taitoja, joita tarvitaan verkossa?",
"Pitäisikö oppilaitoksissa tukea opiskelijoiden kokonaisvaltaista hyvinvointia laajemmin kuin vain opintoihin liittyen?",
"Opiskelijoiden pitäisi voida vaikuttaa enemmän oppilaitoksen toimintaan.",
"Oppilaitoksissa pitäisi panostaa enemmän opiskelijoiden hyvinvointiin.",
"Koen opiskelun mielekkäänä.",
"Opiskelun pitää sisältää enemmän minulle vaikeita tehtäviä.",
"Pitäisikö oppilaitosten tukea sinua enemmän itsenäisessä opiskelussa?",
"Pitäisikö oppilaitoksen tukea sinua enemmän digitaalisten taitojen opiskelussa?",
"Pitäisikö oppilaitosten järjestää enemmän verkko-opiskelua?",
"Uskon pärjääväni hyvin opiskelun jälkeisessä elämässä.",
"Koen voivani vaikuttaa omaan tulevaisuuteeni.",
"Haluan opiskella lisää sen jälkeen, kun valmistun nykyisestä oppilaitoksesta.",
"Minulla on hyvät sosiaaliset taidot.",
"Yhdessä opiskelemalla opin hyvin.",
"Pitäisikö oppilaitoksesi olla enemmän yhdessä opiskelua (esimerkiksi ryhmätöitä)?",
"Pitäisikö oppilaitoksesi tukea enemmän opiskelijoiden kaverisuhteiden muodostumista?",
"Pitäisikö oppilaitoksessasi järjestää tilaisuuksia, joissa voisi tutustua ennestään tuntemattomiin opiskelijoihin?",
"Pitäisikö oppilaitoksessasi olla enemmän yhteisöllistä harrastustoimintaa?",
"Yhdessä opiskeleminen on tärkeää, koska työelämässä tarvitaan ryhmätyötaitoja.",
"Yhdessä opiskelu on hauskaa.",
"Ilmastonmuutokseen liittyvät ongelmat saadaan ratkaistua teknologian avulla.",
"Maahanmuutto on tarpeellista suomalaisen yhteiskunnan hyvinvoinnin kannalta.",
"Pitäisikö ympäristöystävällisyyteen tähtäävien teknologian käyttöä lisätä?",
"Pitäisikö yhteiskunnan tukea enemmän nuorten harrastustoimintaa?",
"Pitäisikö Suomessa olla enemmän työpaikkoja, joihin pääsee ilman tutkintoa?",
"Pitäisikö kansalaisten kansalaisia kannustaa osallistumaan enemmän yhteisistä asioista päättämiseen?",
"Oppilaitoksissa pitäisi olla enemmän nuorisotyöntekijöitä.",
"Suomessa pitäisi kiinnittää enemmän huomiota nuorten yksinäisyydestä johtuviin ongelmiin.",
"Työntekijöiden henkisestä hyvinvoinnista huolehtiminen on tärkeää.",
"Työtä tehdään pääasiassa rahan vuoksi.",
"Pitäisikö työelämän olla vähemmän stressaavaa?",
"Pitäisikö työikäisten voida käyttää enemmän aikaa perheelle, ystäville ja harrastuksille?",
"Pitäisikö työntekijöillä olla mahdollisuus välillä opiskella lisää?",
"Pitäisikö työaikaa tulevaisuudessa vähentää?",
"Etätyömahdollisuus lisää kiinnostustani työpaikkaa kohtaan.",
"Kansainvälinen ilmapiiri lisää kiinnostustani työpaikkaa kohtaan.",
"Haluan opiskella ja valmistua nykyisestä oppilaitoksestani.",
"Aivot ovat kuin lihas ja niitä harjoittelemalla voin vaikuttaa älykkyyteeni.",
"Pidätkö itseäsi sosiaalisesti älykkäänä?",
"Pystyykö sosiaalisia taitoja kehittämään?",
"Voitko itse vaikuttaa siihen, millaiseksi elämäsi muotoutuu?",
"Opiskelutehtävät ovat yleensä liian vaikeita.",
"Tulevaisuus pelottaa minua.",
"Olen enimmäkseen tyytyväinen."],
	main_questions_statement: [
		'Pidän haastavista opiskelutehtävistä, koska niiden suorittaminen on palkitsevaa.',
		'Pidän siitä, että oppilaitoksissa järjestetään myös vapaa-ajan toimintaa.',
		'Digitaitoja on tärkeää opiskella, koska ne auttavat minua saamaan hyvän työpaikan.',
		'Digitaitoja on tärkeää opiskella, koska ne auttavat minua saamaan uusia kavereita.',
		'Pidän siitä, että Suomessa panostetaan koulutukseen, koska niin yhteiskunta voi paremmin.',
		'Pidän siitä, että Suomessa arvostetaan opiskelua.',
		],
	main_questions_question: [
		'Pidän haastavista opiskelutehtävistä, koska niiden suorittaminen on palkitsevaa.',
		'Pidän siitä, että oppilaitoksissa järjestetään myös vapaa-ajan toimintaa.',
		'Digitaitoja on tärkeää opiskella, koska ne auttavat minua saamaan hyvän työpaikan.',
		'Digitaitoja on tärkeää opiskella, koska ne auttavat minua saamaan uusia kavereita.',
		'Pidän siitä, että Suomessa panostetaan koulutukseen, koska niin yhteiskunta voi paremmin.',
		'Pidän siitä, että Suomessa arvostetaan opiskelua.',
	],
};
